package Leetcode33;
import java.lang.Math;

public class Leetcode33Test {
    
    /*
        This method is used to generate a ascending sequence by four given parameteres, minSequenceLength,
        maxSequecneLength, minIncrement and maxIncrement. the first two parameters determine the possible 
        length of the generated sequence as the name of the variable indicated, then the last two parameters 
        indicate the possible increment betwen the adjacent element of the generated sequence. hence, by such 
        configuration, an ascending sequence can be generated by this method.
        the result of the generated sequence is like this :
        [a[0], a[1], ..., a[n]] and satisfies the constraints:
        1.minSequenceLength-1<=n<=maxSequenceLength-1
        2.minIncrement<=a[0]<=maxIncrement
        3.for all 1<=i<=n:  minIncrement<=a[i]-a[i-1]<=maxIncrement
    */
   public static int[] generateAscendingSequence(int minSequenceLength, int maxSequenceLength, int minIncrement,int maxIncrement){
        int sequenceLength=Math.round((float)Math.random()*(maxSequenceLength-minSequenceLength)+minSequenceLength);
        int[] ascendingSequence=new int[sequenceLength];
        ascendingSequence[0]=Math.round((float)Math.random()*(maxIncrement-minIncrement)+minIncrement);
        for (int i=1; i<sequenceLength; i++){
            ascendingSequence[i]=ascendingSequence[i-1]+Math.round((float)Math.random()*(maxIncrement-minIncrement)+minIncrement);
        }
        return ascendingSequence;
    }

    /*
        this method is used to realize the function of the rotation of the given sequence,
        the rotateProbability is to determine the probaility of rotation, if this sequence 
        is determined to be rotated, then the element of this sequence will be replaced by 
        by the given order as the question reqired.
    */ 
    public static int[] rotateAscendingArray(float rotateProbability, int[] ascendingArray){
        if((float)Math.random()<rotateProbability){
            int rotateLocation=Math.round((float)Math.random()*(ascendingArray.length-1-1)+1);
            int[] temp=new int[ascendingArray.length];
            for(int i=0; i<ascendingArray.length; i++){
                temp[i]=ascendingArray[i];
            }
            for(int i=rotateLocation; i<ascendingArray.length; i++){
                ascendingArray[i-rotateLocation]=temp[i];
            }
            for(int i=0; i<rotateLocation; i++){
                ascendingArray[i+ascendingArray.length-rotateLocation]=temp[i];
            }
        }
        return ascendingArray;
    }

    /*
        this method is used to display a given sequence, the first parameter is 
        the pointer of the given array, and the second parameter is the given name
        of the sequence. It should be displayed like this:
        name of the array
        [array[0]  array[1]  ...  array[array.length-1]]
    */
    public static void displayArray(int[] targetArray, String targetArrayName){
        System.out.println(targetArrayName);
        System.out.print("[ ");
        for(int i=0; i<targetArray.length; i++){
            System.out.print(targetArray[i]+" ");
        }
        System.out.println("]");
    }
    
    public static void main(String[] args) {
        // generate an ascending sequence
        int[] intArray=generateAscendingSequence(100,100,1,1);
        // display the sequence generated above
        displayArray(intArray,"original Array");
        // determine the rotateProbability 
        float rotateProbability=(float)0.7;
        // make a possible rotation to the array intArray
        int[] possibilyRotatedArray=rotateAscendingArray((float)rotateProbability, intArray);
        // display the sequence possibilyRotatedArray generated above
        displayArray(possibilyRotatedArray,"Possibly Rotated Array");
        // return the target index of the target value in the squence possibilyRotatedArray
        int targetValue=23;
        System.out.println();
        System.out.println("index for the target value: "+Leetcode33Solution.search(possibilyRotatedArray, targetValue));
    }
}
